/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_projectvoodoo_ocuvstabilitytest_NativeTestLib */

#ifndef _Included_org_projectvoodoo_ocuvstabilitytest_NativeTestLib
#define _Included_org_projectvoodoo_ocuvstabilitytest_NativeTestLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_projectvoodoo_ocuvstabilitytest_NativeTestLib
 * Method:    getMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_projectvoodoo_ocuvstabilitytest_NativeTestLib_getMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
